Parameters:
  ZipBucket:
    Description: Name of the bucket where the SageMaker workshop file is uploaded
    Type: String
    Default: 'ee-assets-prod-us-east-1'
  ZipKey:
    Description: Name of the key to workshop ZIP file
    Type: String
    Default: 'modules/14407b7f52234d749994de6f871933cd/v1/sm-id.zip'

Resources:
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Policies: 
        - PolicyName: s3-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: arn:aws:s3:::*
        - PolicyName: iam-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:GetRolePolicy
                Resource: '*'
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - 
            Effect: Allow
            Principal: 
              Service: 
                - sagemaker.amazonaws.com
            Action: 
              - sts:AssumeRole                
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AWSCloudFormationFullAccess'
        - 'arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess'

  SageMakerImmersionDayRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      Code:
        S3:
          Bucket: !Ref ZipBucket
          Key: !Ref ZipKey
      RepositoryDescription: Repository for the ML models/images code
      RepositoryName: sagemaker-immersion-day-repository

  SageMakerImmersionDayNotebook: 
    Type: AWS::SageMaker::NotebookInstance
    Properties: 
      DefaultCodeRepository: !GetAtt SageMakerImmersionDayRepository.CloneUrlHttp
      DirectInternetAccess: Enabled
      InstanceType: ml.t3.medium
      NotebookInstanceName: sagemaker-immersion-day
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      RootAccess: Enabled
      VolumeSizeInGB: 5      

  MLOpsRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "Admin"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"
Outputs:
  MLOpsRole:
    Description: MLOPsRole
    Value: !GetAtt MLOpsRole.Arn
    Export:
      Name: MLOpsRole
  SageMakerImmersionDayRepository:
    Description: SageMakerImmersionDayRepository
    Value: !GetAtt SageMakerImmersionDayRepository.Name
    Export:
      Name: SageMakerImmersionDayRepository